# Generated by Django 4.2.23 on 2025-07-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRAS_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='rider_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='image',
            field=models.BinaryField(),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['timestamp'], name='SRAS_App_vi_timesta_baafe1_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['rider_hash'], name='SRAS_App_vi_rider_h_872003_idx'),
        ),
    ]
