# Generated by Django 5.1.4 on 2025-09-07 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRAS_App', '0002_violation_rider_hash_alter_violation_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.BinaryField()),
                ('rider_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('violation_type', models.CharField(default='No Helmet', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRAS_App.camera')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='SRAS_App_vi_timesta_138c59_idx'), models.Index(fields=['rider_hash'], name='SRAS_App_vi_rider_h_894c4e_idx'), models.Index(fields=['status'], name='SRAS_App_vi_status_febd5a_idx')],
            },
        ),
    ]
