# Generated by Django 5.1.4 on 2025-09-07 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRAS_App', '0003_violationstaging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violationstaging',
            name='violation_type',
        ),
        migrations.AddField(
            model_name='violation',
            name='staging_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SRAS_App.violationstaging'),
        ),
    ]
