# Generated by Django 5.1.4 on 2025-09-07 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRAS_App', '0004_remove_violationstaging_violation_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='staging_record',
        ),
        migrations.CreateModel(
            name='StagingViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.BinaryField()),
                ('rider_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRAS_App.camera')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ViolationStaging',
        ),
        migrations.AddIndex(
            model_name='stagingviolation',
            index=models.Index(fields=['timestamp'], name='SRAS_App_st_timesta_f51ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='stagingviolation',
            index=models.Index(fields=['rider_hash'], name='SRAS_App_st_rider_h_4642ad_idx'),
        ),
        migrations.AddIndex(
            model_name='stagingviolation',
            index=models.Index(fields=['status'], name='SRAS_App_st_status_81e24e_idx'),
        ),
    ]
