# Generated by Django 5.1.4 on 2025-09-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SRAS_App', '0006_violationstaging_delete_stagingviolation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViolationStaging',
        ),
    ]
