# Generated by Django 5.1.4 on 2025-09-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRAS_App', '0007_delete_violationstaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='plate_number',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
