# Generated by Django 5.1.4 on 2025-09-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRAS_App', '0008_alter_violation_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
