# Generated by Django 5.1.4 on 2025-09-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRAS_App', '0009_alter_violation_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='plate_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
