# Generated by Django 5.1.4 on 2025-09-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SRAS_App', '0011_authtoken_authtoken_sras_app_au_user_id_8b771d_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
