# Generated by Django 5.2.6 on 2025-09-20 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRAS_App', '0013_violation_status_violation_verification_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.BinaryField()),
                ('plate_image', models.BinaryField(blank=True, null=True)),
                ('rider_hash', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='violation',
            name='SRAS_App_vi_status_5156e4_idx',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='status',
        ),
        migrations.AddField(
            model_name='violationstaging',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRAS_App.camera'),
        ),
        migrations.AddIndex(
            model_name='violationstaging',
            index=models.Index(fields=['timestamp'], name='SRAS_App_vi_timesta_138c59_idx'),
        ),
        migrations.AddIndex(
            model_name='violationstaging',
            index=models.Index(fields=['rider_hash'], name='SRAS_App_vi_rider_h_894c4e_idx'),
        ),
    ]
