# Generated by Django 5.2.6 on 2025-09-20 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRAS_App', '0014_violationstaging_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violationstaging',
            name='camera',
        ),
        migrations.AddField(
            model_name='violation',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_verification', max_length=20),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['status'], name='SRAS_App_vi_status_5156e4_idx'),
        ),
        migrations.DeleteModel(
            name='ViolationStaging',
        ),
    ]
