# Generated by Django 5.2.6 on 2025-09-20 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRAS_App', '0015_remove_violationstaging_camera_violation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.BinaryField()),
                ('plate_image', models.BinaryField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('sms_sent', models.BooleanField(default=False)),
                ('rider_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRAS_App.camera')),
                ('original_violation', models.ForeignKey(blank=True, help_text='Reference to the original violation that was approved', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SRAS_App.violation')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='SRAS_App_or_timesta_b71430_idx'), models.Index(fields=['rider_hash'], name='SRAS_App_or_rider_h_977813_idx'), models.Index(fields=['verified_at'], name='SRAS_App_or_verifie_9dff9c_idx')],
            },
        ),
    ]
